name = "codecrafters_redis"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "~> 0.43 or ~> 1.0"
gleam_erlang = "~> 0.28"
gleam_otp = "~> 0.14.1"
glisten = "~> 6.0"

[dev-dependencies]
gleeunit = "~> 1.2.0"
